def data():
    study_abroad_dict = {
        "Clark-in-Madrid(Spain) - Semester": {
            "index":0,
            "year": ["Sophomore", "Junior", "Senior"],
            "school": ["A. James Clark School of Engineering"],
            "gpa": 3.0,
            "purpose": ["academic"],
            "region": ["Europe"],
            "seclang": ["Spanish"],
            "cost": 18650,
            "housing": ["Host", "Apartment"],
            "extra": ["organized trips","outdoor activities"],
            "length": ["Semester - Spring", "Semester - Fall"],
            "credit": ["transfer"]
            },
        "Global Entrepreneurship Semester in Seoul": {
            "index":0,
            "year": ["Sophomore", "Junior", "Senior"],
            "school": [],
            "gpa": 3.0,
            "purpose": ["internship"],
            "region": ["Asia"],
            "seclang": ["Korean"],
            "cost": 28629,
            "housing": ["Campus"],
            "extra": ["sports", "career development"],
            "length": ["Semester - Spring"],
            "credit": ["transfer","resident"]
        },
        "Maryland-in-Berlin(Germany) - Full Year": {
            "index":0,
            "year": ["Sophomore", "Junior", "Senior"],
            "school": [],
            "gpa": 3.0,
            "purpose": ["academic"],
            "region": ["Europe"],
            "seclang": ["German"],
            "cost": 33080,
            "housing": ["Host", "Apartment"],
            "extra": ["organized trips", "educational"],
            "length": ["Full Year"],
            "credit": ["transfer", "resident"]
        },
        "Maryland-in-Buenos-Aires(Argentina) - Semester": {
            "index": 0,
            "year": ["Sophomore", "Junior", "Senior"],
            "school": [],
            "gpa": 2.75,
            "purpose": ["academic"],
            "region": ["America"],
            "seclang": ["Spanish", "Portuguese"],
            "cost": 18370,
            "housing": ["Host"],
            "extra": ["outdoor activities", "sports", "career development"],
            "length": ["Semester - Spring"],
            "credit": ["transfer", "resident"]
        },
        "Maryland-in-Copenhagen(Denmark) - Full Year": {
            "index": 0,
            "year": ["Sophomore", "Junior", "Senior"],
            "school": [],
            "gpa": 3.0,
            "purpose": ["academic"],
            "region": ["Europe"],
            "seclang": [],
            "cost": 52990,
            "housing": ["Host", "Apartment"],
            "extra": ["outdoor activities", "sports"],
            "length": ["Full Year"],
            "credit": ["transfer", "resident"]
        },
        "Maryland-in-Florence(Italy) - Semester": {
            "index": 0,
            "year": ["Sophomore", "Junior", "Senior"],
            "school": [],
            "gpa": 2.75,
            "purpose": ["academic"],
            "region": ["Europe"],
            "seclang": ["Italian"],
            "cost": 20950,
            "housing": ["Apartment"],
            "extra": ["outdoor activities", "sports", "volunteer"],
            "length": ["Semester - Spring","Semester - Fall"],
            "credit": ["transfer", "resident"]
        },
        "Maryland-in-Nice(France) - Full Year": {
            "index": 0,
            "year": ["Sophomore", "Junior", "Senior"],
            "school": [],
            "gpa": 2.75,
            "purpose": ["academic"],
            "region": ["Europe"],
            "seclang": ["French"],
            "cost": 32790,
            "housing": ["Apartment", "Host"],
            "extra": ["organized trips"],
            "length": ["Full Year"],
            "credit": ["transfer", "resident"]
        },
        "BMGT Exchange: RMIT (Royal Melbourne Institute of Technology) (Australia)": {
            "index": 0,
            "year": ["Sophomore", "Junior", "Senior"],
            "school": ["Robert H. Smith School of Business"],
            "gpa": 3.0,
            "purpose": ["academic"],
            "region": ["Oceania"],
            "seclang": [],
            "cost": 31796,
            "housing": ["Apartment"],
            "extra": ["outdoor activities", "educational"],
            "length": ["Semester - Spring","Semester - Fall"],
            "credit": ["transfer"]
        },
        "University of Maryland Hong Kong Exchange": {
            "index": 0,
            "year": ["Sophomore", "Junior", "Senior"],
            "school": [],
            "gpa": 3.0,
            "purpose": ["academic"],
            "region": ["Asia"],
            "seclang": ["Chinese"],
            "cost": 25661,
            "housing": ["Campus"],
            "extra": ["organized trips", "educational"],
            "length": ["Semester - Spring", "Semester - Fall"],
            "credit": ["transfer"]
        },
    }
    return study_abroad_dict
